Update appearance
* Added Afterglow-Catppuccin-Mauve-v2 cursor theme
* Added catppuccin color theme for nvim

diff --git a/.local/bin/change-cursor-theme b/.local/bin/change-cursor-theme
--- a/.local/bin/change-cursor-theme
+++ b/.local/bin/change-cursor-theme
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 cursor_themes=(
+    "Afterglow-Catppuccin-Mauve-v2"
     "ArcAurora-cursors"
     "ArcDusk-cursors"
     "ArcMidnight-cursors"
@@ -14,6 +15,7 @@ cursor_themes=(
 )
 
 cursor_theme_urls=(
+    "https://www.gnome-look.org/p/2059528"
     "https://www.gnome-look.org/p/1665694"
     "https://www.gnome-look.org/p/1652458"
     "https://www.gnome-look.org/p/1659743"
@@ -44,17 +46,20 @@ if [[ ! " ${cursor_themes[*]} " =~ " ${1} " ]]; then
 fi
 
 cursor_theme=${1}
-if [ -z ${2+x} ]; then
-    cursor_size="24"
-else
-    cursor_size=${2}
-fi
+cursor_size=${2:-"24"}
+
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m' # No Color
 
 share_icons_dir=${HOME}/.local/share/icons
 if [ ! -d ${share_icons_dir}/${cursor_theme} ]; then
     [ ! -d ${share_icons_dir} ] && mkdir -p ${share_icons_dir}
     wget -q --show-progress -P /tmp \
         https://ewr1.vultrobjects.com/cursors/${cursor_theme}.tar.gz
+    [ ! $? -eq 0 ] \
+        && printf "${RED}Error: failed to download cursor theme${NC}\n" \
+        && exit 1
     tar xf /tmp/${cursor_theme}.tar.gz -C ${share_icons_dir}
     rm /tmp/${cursor_theme}.tar.gz
 fi
@@ -73,10 +78,6 @@ update_param () {
         sed -i -e "s/^\(${param}${separator}\)\(.*\)/\1${value}/" ${path}
     fi
 }
-
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-NC='\033[0m' # No Color
 
 printf "Updating gtk3 settings... "
 gtk3_settings=${HOME}/.config/gtk-3.0/settings.ini
@@ -113,7 +114,7 @@ update_param ${index_theme} "Inherits" ${cursor_theme} "=" \
     && printf "${GREEN}Done!${NC}\n" \
     || printf "${RED}Error!${NC}\n"
 
-printf "Creating link to new cursors..."
+printf "Creating link to new cursors... "
 ln -s -f ${share_icons_dir}/${cursor_theme}/cursors ${icons_default_dir} \
     && printf "${GREEN}Done!${NC}\n" \
     || printf "${RED}Error!${NC}\n"
